name: Manual Workflow


on:
  pull_request_target:
    types: [opened, reopened]
  workflow_dispatch:

jobs:
  pull-request-check:
    name: PR validation
    runs-on: ubuntu-latest

    steps:
      - name: Confirm PR
        run: |
          echo "PR #${{ github.event.pull_request.number || github.event.number }}"
          echo "Jira integration disabled."


          
